PR-Arithmetics-Exercises
DarjaLeonova/CODELEX-Exercsises pull request #2
Opened 2022-07-25 17:40 UTC by DarjaLeonova

Done all exercises, please review.

2022-07-25 19:37 UTC, ausmoons requested changes

2022-07-25 19:37 UTC, ausmoons commented on exercises/Arithmetic/CalculateArea-Ex-10/Program.cs
> +            } else if (userChoice == 2)
else if jaunā rindā

2022-07-25 19:37 UTC, ausmoons commented on exercises/Arithmetic/CalculateArea-Ex-10/Program.cs
Pēdējais var būt else

2022-07-25 19:37 UTC, ausmoons commented on exercises/Arithmetic/Exercise-1/Program.cs
> +            return  x + y == number || Math.Abs(x - y) == number ? true : false;
return  x + y == number || Math.Abs(x - y) == number

2022-07-25 19:37 UTC, ausmoons commented on exercises/Arithmetic/Exercise-11/Exercise-11.csproj
> +    <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"
[exercises/Arithmetic/Exercise-1/**obj**/Debug/Exercise_1.pdb](https://github.com/DarjaLeonova/CODELEX-Exercsises/pull/2/files#diff-6a26c3dbb89896a1feae8b5debb9c2d8f4114039e6d68754585e9d50088f2df0)

2022-07-25 19:37 UTC, ausmoons commented on exercises/Arithmetic/Exercise-11/Exercise-11.csproj
> +    <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"
obj mapēm nav jābūt

2022-07-25 19:37 UTC, ausmoons commented on exercises/Arithmetic/Exercise-11/Program.cs
> +            } else if (nums % 7 == 0)
else if jaunā rindā

2022-07-25 19:37 UTC, ausmoons commented on exercises/Arithmetic/Exercise-8/Program.cs
> +            if (hoursWorked > 40 && hoursWorked < maxHoursWorked)
pirms jauna if tukša rinda vajadzīga

2022-07-26 10:06 UTC, DarjaLeonova commented
Please Review again.
The commit - Fixes after PR for review - contains code fixes
The commit - deleting rest obj folders-1 , deleting rest obj folders-2 - contains obj folders deletions

2022-07-26 18:20 UTC, ausmoons commented on exercises/Arithmetic/CalculateArea-Ex-10/Program.cs
> +namespace CalculateArea_Ex_10
Vēl ir lieks fails 
![image](https://user-images.githubusercontent.com/53189160/181081901-c9ec7bf8-5288-4c4a-92d9-4a469e499344.png)

2022-07-26 18:20 UTC, ausmoons commented on exercises/Arithmetic/Exercise-8/Program.cs
> +            if (hoursWorked > 40 && hoursWorked < maxHoursWorked)
Neredzu labojumu

2022-07-26 18:21 UTC, ausmoons approved these changes
Izņem liekos failus un tad vari mergot

2022-07-26 18:44 UTC, ausmoons requested changes
Tev

2022-07-26 18:44 UTC, ausmoons commented on exercises/Arithmetic/CalculateArea-Ex-10/CalculateArea-Ex-10.csproj
> +    <PropertyGroup>
![image](https://user-images.githubusercontent.com/53189160/181085983-821e80fd-c008-4bf7-83f7-8ad314fdc369.png)
 es neredzu visus uzd

2022-07-26 19:06 UTC, DarjaLeonova commented
Ar pēdējo komituizlaboju visas kļūdas un tagad vajadzētu būt redzams pārējiem projektiem

2022-07-26 19:23 UTC, ausmoons approved these changes

2022-07-26 20:08 UTC, merged